baseURL = "http://www.chezmoi.io/"
languageCode = "en-us"
theme = "book"
title = "chezmoi.io"

[params]
    BookDateFormat = "2006-02-01"
    BookLogo = "logo-144px.svg"
    BookMenuBundle = "/menu"
    BookRepo = "https://github.com/twpayne/chezmoi"
    BookToC = 3