language: go

addons:
  apt:
    packages:
    # needed for goreleaser/nfpm:
    - rpm

go:
  - 1.12.x

env:
  - GO111MODULE=on

install:
  - go get golang.org/x/lint/golint
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go test -race ./...
  - go vet ./...
  - golint ./...
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

sudo: false

# calls goreleaser
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
