language: go

addons:
  apt:
    packages:
    - rpm

go:
- 1.12.x

env:
- GO111MODULE=on

install:
- go mod download
- GO111MODULE=off go get golang.org/x/tools/cmd/cover
- GO111MODULE=off go get github.com/golangci/golangci-lint/cmd/golangci-lint
- GO111MODULE=off go get github.com/mattn/goveralls
- GO111MODULE=off go get github.com/wadey/gocovmerge
- GO111MODULE=off go get mvdan.cc/gofumpt
- GO111MODULE=off go get mvdan.cc/gofumpt/gofumports

script:
- make generate
- make format
- go mod tidy
- git diff --exit-code
- make test
- make lint
- make coverage.out
- go run . --version
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN; fi

sudo: false

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
