name: lock-threads

on:
  schedule:
  - cron: 17 2 * * *
  workflow_dispatch: {}

permissions:
  issues: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  action:
    runs-on: ubuntu-22.04
    steps:
    - uses: dessant/lock-threads@7266a7ce5c1df01b1c6db85bf8cd86c737dadbe7 # v6.0.0
      with:
        process-only: issues, prs
        issue-lock-reason: resolved
        issue-inactive-days: 28
        pr-lock-reason: resolved
        pr-inactive-days: 28
        log-output: true
